import Head from "next/head";
import Link from "next/link";
import { Button } from "~/components/ui/button";
import { Moon, Sun } from "lucide-react";
import { api } from "~/utils/api";
import { useTheme } from "next-themes";

export default function Home() {
  const hello = api.post.hello.useQuery({ text: "World" });

  const apiUtils = api.useUtils();
  const handleInvalidateQuery = async () => {
    await apiUtils.post.hello.invalidate();
  };

  const { setTheme } = useTheme();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center gap-y-6">
        <h1>Hello World</h1>
        <Button
          onClick={() => setTheme("dark")}
          size={"icon"}
          variant={"secondary"}
        >
          <Moon />
        </Button>
        <Button
          onClick={() => setTheme("light")}
          size={"icon"}
          variant={"secondary"}
        >
          <Sun />
        </Button>
      </main>
    </>
  );
}
